FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY load_balancer.py .
COPY consistent_hash.py .

EXPOSE 5000

CMD ["python", "load_balancer.py"]